export const REPAIR_SERVICES = [
  { name: 'Engine Repair', defaultPrice: 12000 },
  { name: 'Brake Repair', defaultPrice: 1800 },
  { name: 'Transmission Repair', defaultPrice: 15000 },
  { name: 'Suspension Repair', defaultPrice: 6500 },
  { name: 'Exhaust Repair', defaultPrice: 2500 },
  { name: 'Electrical Repair', defaultPrice: 1500 },
  { name: 'AC Repair', defaultPrice: 2500 },
  { name: 'Tire Replacement', defaultPrice: 3500 },
  { name: 'Wheel Alignment', defaultPrice: 600 },
  { name: 'Body Work', defaultPrice: 1500 },
  { name: 'Paint Job', defaultPrice: 2500 },
  { name: 'Hydraulic System Repair', defaultPrice: 3000 },
  { name: 'Cooling System Repair', defaultPrice: 2000 },
  { name: 'Fuel System Repair', defaultPrice: 3500 },
  { name: 'Steering Repair', defaultPrice: 4500 },
  { name: 'Clutch Repair', defaultPrice: 8500 },
  { name: 'Battery Replacement', defaultPrice: 4500 },
  { name: 'General Service', defaultPrice: 3500 },
];
